version: 2

jobs:
  # The build job
  build:
    working_directory: ~/flingo
    docker:
      - image: circleci/node:latest-browsers

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  # The test job
  test:
    working_directory: ~/flingo
    docker:
      - image: circleci/node:latest-browsers

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      # Lint the source code
      - run:
          name: Linting
          command: npm run affected:lint
      # Test the source code
      - run:
          name: Unit testing
          command: npm run affected:test

      - run:
          name: 2e2 testing
          command: npm run affected:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
